tags:
- name: ip
  description: IP API

paths:
# [POST] ip
  /ip:
    post:
      summary: Pass ip address list to be screened

      requestBody:
        description: A list of IP addresses as strings
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/ipList'

      responses:
        200:
          description: 'Success'

# definitions
definitions:
  ipList:
    type: array
    description: List of IP's to check against the blacklist


schemes:
 - https
 - http
